### ISSUE TITLE
name 'yaml' is not defined

### ISSUE THREAD

**Issue by hoshino114** [barbarbar338/hammer-csgo-hack#2]
Is it really not banned by **VAC**?

__Without_ being reported_.

**Comment by barbarbar338** [comment]
It probably will VAC ban now because not updated offsets and other things but my testing account is still not banned for now

**Comment by hoshino114** [comment]
> It probably will VAC ban now because not updated offsets and other things but my testing account is still not banned for now

oh，it's good , But this python program has an error on my computer
![image](https://user-images.githubusercontent.com/110707694/192205046-846a11bd-20e4-43a3-ae78-72cccee38621.png)

**Comment by barbarbar338** [comment]
This is not because of VAC ban :?

First you have to install dependencies and build the executable. You can find instructions on `README.md` file. And then you can make your own config and can run executable. 

If this error persists after installing packages let me know.

Edit: do not forget to update offsets and do not use this on competitive games <3

**Comment by hoshino114** [comment]
> 

Can I run the python program directly？

**Comment by barbarbar338** [comment]
Yes you can, give it a try.

**Comment by barbarbar338** [comment]
looks like everything is okay. Closing issue.
